// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag"`
	ContainerName   string `form:"containerName"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name"`
	NewName         string `json:"new_name"`
	ImageNameAndTag string `json:"image_name_and_tag"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid"`
}

type IdReq struct {
	Id string `path:"id"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey,optional"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	Name string `json:"name"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type RenameContainerReq struct {
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name"`
}

type StopContainerReq struct {
	Name string `json:"name"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt,optional"`
}

type VersionMsgResp struct {
	Version   string `json:"version"`
	BuildDate string `json:"build_date"`
}

type VersionReq struct {
	Type string `form:"type"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag"`
}

// --- 容器日志 ---

type ContainerLogsReq struct {
	IdReq
	Tail int `form:"tail,default=100"`
}

type ContainerLogsResp struct {
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}

// --- Compose 管理 ---

type ComposeUpdateReq struct {
	Name       string `json:"name"`
	WorkingDir string `json:"working_dir"`
	ConfigFile string `json:"config_file,optional"`
}

type ComposeProjectInfo struct {
	Name       string   `json:"name"`
	WorkingDir string   `json:"workingDir"`
	ConfigFile string   `json:"configFile"`
	Containers []string `json:"containers"`
}

// --- 容器日志 ---

type ContainerLogsReq struct {
	IdReq
	Tail int `form:"tail,default=100"`
}

type ContainerLogsResp struct {
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}

// --- 容器执行 ---

type ContainerExecReq struct {
	IdReq
	Cmd []string `json:"cmd"`
}

// --- 批量操作 ---

type BatchContainerReq struct {
	IDs    []string `json:"ids"`
	Action string   `json:"action"` // stop / restart / start / remove
}

// --- Compose ---

type ComposeUpdateReq struct {
	Name       string `json:"name"`
	WorkingDir string `json:"working_dir"`
	ConfigFile string `json:"config_file,optional"`
}

type ComposeProjectInfo struct {
	Name       string   `json:"name"`
	WorkingDir string   `json:"workingDir"`
	ConfigFile string   `json:"configFile"`
	Containers []string `json:"containers"`
	Status     string   `json:"status"`
}

type ComposeLogsReq struct {
	Name       string `json:"name"`
	WorkingDir string `json:"working_dir"`
	ConfigFile string `json:"config_file,optional"`
	Tail       string `json:"tail,optional"`
}

// --- 系统管理 ---

type RemoveVolumeReq struct {
	Name  string `json:"name"`
	Force bool   `json:"force,default=false"`
}
