// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/atpx4869/dockpit/internal/handler/auth"
	container "github.com/atpx4869/dockpit/internal/handler/container"
	icons "github.com/atpx4869/dockpit/internal/handler/icons"
	image "github.com/atpx4869/dockpit/internal/handler/image"
	progress "github.com/atpx4869/dockpit/internal/handler/progress"
	system "github.com/atpx4869/dockpit/internal/handler/system"
	version "github.com/atpx4869/dockpit/internal/handler/version"
	"github.com/atpx4869/dockpit/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			// --- 原有功能 ---
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
			// --- 新增功能 ---
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/logs",
				Handler: container.LogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/stats",
				Handler: container.StatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers/stats",
				Handler: container.StatsAllHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/exec",
				Handler: container.ExecHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/containers/batch",
				Handler: container.BatchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/health",
				Handler: container.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers/health",
				Handler: container.HealthAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/list",
				Handler: container.ComposeListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/update",
				Handler: container.ComposeUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/logs",
				Handler: container.ComposeLogsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// --- 系统管理 ---
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/system/disk",
				Handler: system.DiskUsageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/disk/cleanup",
				Handler: system.DiskCleanupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/networks",
				Handler: system.NetworkListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/system/network/:id",
				Handler: system.NetworkRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/volumes",
				Handler: system.VolumeListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/system/volume/:id",
				Handler: system.VolumeRemoveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
